Repository rilling/argoumlFall2024, pull requests merged in 2024-11, with the labels that each got.

#2 Technical Debt Analysis and Resolution – Group 18 Submission
  src/argouml-app/src/org/argouml/application/Main.java
  src/argouml-app/src/org/argouml/application/api/Argo.java
  src/argouml-app/src/org/argouml/cognitive/ToDoItem.java
  src/argouml-app/src/org/argouml/cognitive/ui/AddToDoItemDialog.java
  src/argouml-app/src/org/argouml/configuration/ConfigurationProperties.java
  src/argouml-app/src/org/argouml/persistence/DiagramMemberFilePersister.java
  src/argouml-app/src/org/argouml/persistence/SAXParserBase.java
  src/argouml-app/src/org/argouml/persistence/UmlFilePersister.java
  src/argouml-app/src/org/argouml/uml/generator/AbstractSection.java
  src/argouml-app/src/org/argouml/uml/generator/TempFileUtils.java
  src/argouml-core-diagrams-activity2/src/org/argouml/activity2/diagram/BaseDiagram.java
  src/argouml-core-model-mdr/src/org/argouml/model/mdr/XmiReaderImpl.java
  src/argouml-core-umlpropertypanels/src/org/argouml/core/propertypanels/model/MetaDataCache.java
Labels: technical debt, Group 18

#38 Clone detection and removal – Group 18 - Case Study 2
  .idea/.gitignore
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/jarRepositories.xml
  .idea/vcs.xml
  src/argouml-app/src/org/argouml/cognitive/ui/ToDoByDecision.java
  src/argouml-app/src/org/argouml/cognitive/ui/ToDoByGoal.java
  src/argouml-app/src/org/argouml/cognitive/ui/ToDoByType.java
  src/argouml-app/src/org/argouml/uml/diagram/state/ui/FigConcurrentRegion.java
  src/argouml-app/src/org/argouml/uml/ui/AbstractActionAddModelElement2.java
  src/argouml-app/src/org/argouml/uml/ui/foundation/core/ActionAddClientDependencyAction.java
  src/argouml-app/src/org/argouml/uml/ui/foundation/core/ActionAddSupplierDependencyAction.java
Labels: Group 18, Removing Software Clones

#44 Group 17 - Case Study 2 - Clone detection and removal using CPD of PMD
  src/argouml-app/pom.xml
  src/argouml-app/src/org/argouml/cognitive/ui/ToDoByPriority.java
  src/argouml-app/src/org/argouml/uml/cognitive/critics/CrMissingClassName.java
  src/argouml-app/src/org/argouml/uml/cognitive/critics/CrMissingStateName.java
  src/argouml-app/src/org/argouml/uml/cognitive/critics/CrUML.java
  src/argouml-app/src/org/argouml/uml/diagram/ui/ActionAggregation.java
  src/argouml-app/src/org/argouml/uml/diagram/ui/ActionHelper.java
  src/argouml-app/src/org/argouml/uml/diagram/ui/ActionMultiplicity.java
  src/argouml-app/src/org/argouml/uml/diagram/ui/FigNodeModelElement.java
  src/argouml-core-umlpropertypanels/src/org/argouml/core/propertypanels/ui/RowSelector.java
Labels: Group 17, Removing Software Clones
